
"""
Strategic Analyzer Bot.

Generates live BUY signals only when the latest closed candle satisfies the
entry conditions generated by the best genetic DNA. Fitness is confidence, not
the trigger itself.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Dict, List, Optional

import pandas as pd
from loguru import logger
from sqlalchemy import text

from bots.evaluator.bot import StrategyEvaluator
from config.config_manager import config
from scripts.database import db
from scripts.redis_manager import redis_manager
from scripts.symbol_universe import symbol_universe


class StrategicAnalyzer:
    def __init__(self):
        self.logger = logger.bind(bot="strategic_analyzer")
        self.bot_config = config.get_bot_config("strategic_analyzer") or {"max_signals_per_run": 100}

    def _get_best_genetic_strategy(self, symbol: str) -> Optional[Dict]:
        try:
            with db.get_session() as session:
                row = session.execute(text("""
                    SELECT profit_objective, fitness_score, dna
                    FROM genetic.strategies
                    WHERE symbol = :symbol AND fitness_score > 0
                    ORDER BY fitness_score DESC
                    LIMIT 1
                """), {"symbol": symbol}).fetchone()
                if not row:
                    return None
                import json
                return {
                    "objective": row[0],
                    "fitness": float(row[1]),
                    "dna": row[2] if isinstance(row[2], dict) else json.loads(row[2]),
                }
        except Exception as exc:
            self.logger.error("strategy_fetch_failed symbol={} error={}", symbol, exc)
            return None

    def _fetch_recent_closed_candles(self, symbol: str, timeframe: str, limit: int = 200) -> pd.DataFrame:
        with db.get_session() as session:
            rows = session.execute(text("""
                SELECT time, open, high, low, close, volume
                FROM market_data.ohlcv
                WHERE symbol = :symbol
                  AND timeframe = :timeframe
                  AND time < NOW()
                ORDER BY time DESC
                LIMIT :limit
            """), {"symbol": symbol, "timeframe": timeframe, "limit": limit}).fetchall()
        if not rows:
            return pd.DataFrame(columns=["time", "open", "high", "low", "close", "volume"])
        df = pd.DataFrame(rows, columns=["time", "open", "high", "low", "close", "volume"])
        df = df.sort_values("time").reset_index(drop=True)
        for col in ["open", "high", "low", "close", "volume"]:
            df[col] = df[col].astype(float)
        return df

    def _generate_current_signal_from_dna(self, symbol: str, strategy: Dict) -> Optional[Dict]:
        dna = dict(strategy.get("dna") or {})
        dna["symbol"] = symbol
        dna["profit_objective"] = strategy.get("objective", dna.get("profit_objective", "scalping"))
        timeframe = dna.get("timeframe") or config.get_nested("profit_objectives", dna["profit_objective"], "timeframe", default="1m")

        df = self._fetch_recent_closed_candles(symbol, timeframe, limit=max(200, config.get_nested("filters", "min_candles", default=30) * 4))
        min_candles = int(config.get_nested("filters", "min_candles", default=30))
        if len(df) < min_candles:
            self.logger.info("insufficient_closed_candles symbol={} timeframe={} candles={}", symbol, timeframe, len(df))
            return None

        evaluator = StrategyEvaluator(db_pool="provided")
        df = evaluator._compute_indicators(df, dna)
        df = evaluator._generate_signals(df, dna)
        latest = df.iloc[-1]
        enter_long = bool(latest.get("enter_long", False))
        exit_long = bool(latest.get("exit_long", False))
        fitness = float(strategy.get("fitness", 0.0))

        if enter_long and not exit_long:
            return {
                "symbol": symbol,
                "signal": "BUY",
                "strategy": f"Genetic_{strategy['objective']}",
                "confidence": max(0.0, min(0.99, fitness)),
                "price": float(latest["close"]),
                "timestamp": datetime.now(timezone.utc),
                "timeframe": timeframe,
                "metadata": {"source": "genetic_last_closed_candle", "fitness": fitness, "candle_time": str(latest["time"])},
            }
        self.logger.debug("no_current_signal symbol={} timeframe={} enter_long={} exit_long={} fitness={:.4f}", symbol, timeframe, enter_long, exit_long, fitness)
        return None

    def _analyze_with_genetic_strategy(self, symbol: str, strategy: Dict) -> Optional[Dict]:
        try:
            return self._generate_current_signal_from_dna(symbol, strategy)
        except Exception as exc:
            self.logger.error("genetic_signal_failed symbol={} error={}", symbol, exc)
            return None

    def _save_signal(self, signal: Dict) -> bool:
        try:
            with db.get_session() as session:
                session.execute(text("""
                    INSERT INTO strategies.signals
                    (timestamp, symbol, strategy_name, signal_type, confidence, price, timeframe, metadata)
                    VALUES (:timestamp, :symbol, :strategy, :signal, :confidence, :price, :timeframe, CAST(:metadata AS jsonb))
                """), {**signal, "metadata": __import__("json").dumps(signal.get("metadata", {}), ensure_ascii=False)})
                session.commit()
            return True
        except Exception as exc:
            self.logger.error("signal_save_failed symbol={} error={}", signal.get("symbol"), exc)
            return False

    def run(self, symbols: List[str] = None) -> List[Dict]:
        self.logger.info("strategic_analyzer_start mode=genetic_last_closed_candle")
        if symbols:
            active_symbols = symbols
        else:
            active_symbols, _ = symbol_universe.get_active_universe(timeframe="1m", use_cache=True, include_awakening=True)
        if not active_symbols:
            self.logger.warning("no_active_symbols")
            return []

        all_signals: List[Dict] = []
        pending_genetic: List[str] = []
        max_signals = int(self.bot_config.get("max_signals_per_run", 100))
        for symbol in active_symbols:
            if len(all_signals) >= max_signals:
                break
            best_strategy = self._get_best_genetic_strategy(symbol)
            if not best_strategy:
                pending_genetic.append(symbol)
                continue
            signal = self._analyze_with_genetic_strategy(symbol, best_strategy)
            if signal:
                all_signals.append(signal)
                self.logger.success("signal_generated symbol={} signal={} confidence={:.2f}", signal["symbol"], signal["signal"], signal["confidence"])

        saved = sum(1 for signal in all_signals if self._save_signal(signal))
        if pending_genetic:
            redis_manager.set("scientist:pending_symbols", pending_genetic[:50], ttl=3600)
        self.logger.success("strategic_analyzer_complete signals={} saved={} pending_genetic={}", len(all_signals), saved, len(pending_genetic))
        return all_signals


if __name__ == "__main__":
    StrategicAnalyzer().run()
